### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by aldodemi** [lpgera/dirigera-web#1017]
It would be nice and useful to have the version number somewhere on the homepage.
Thanks
Aldo

**Comment by lpgera** [comment]
Hi @aldodemi,

I'm glad you find the app useful! :) At the moment this project doesn't have a version number, but I'm happy to come up with a solution if that helps the userbase. New versions are published quite frequently, often multiple times a day, so I'm wondering that maybe a date-based build number would make more sense than semantic versioning.

Could you tell me more about what you'd like to see? And when you say "somewhere on the homepage", are you referring to the GitHub page or the Dirigera Web app's login page?

**Comment by aldodemi** [comment]
First of all I found your application very nice so thank you for your works!
My request to have the version number would be to understand if and when the application needs to be updated.
In reality my request was to have the version number on the Dirigera web app page, but I realize that it would be of little use if the corresponding number wasn't also on github...
thanks again for everything

**Comment by lpgera** [comment]
@aldodemi I came up with a solution which I believe should work for you. Let me know if you have any feedback!
