### ISSUE TITLE
git clone may be in error?

### ISSUE THREAD

**Issue by aldodemi** [lpgera/dirigera-web#1348]
in the "Running with Node.js natively" the command: "git clone git@github.com:lpgera/dirigera-web.git" it is possible that it must be "git clone https://github.com/lpgera/dirigera-web.git"?

**Comment by lpgera** [comment]
It depends on how you want to use GitHub. The one in the readme is for SSH key based authentication. But you're correct that people without a GitHub account or without an SSH key will have to use the HTTPS protocol for cloning. I'm going to update this in the readme soon.
